### ISSUE TITLE
Problem with PostgreSQL

### ISSUE THREAD

**Issue by LegendORC** [bleroy/vandelay#51]
Hello,

I have some problem with `PostgreSQL` when i try to enable `Vandelay Meta` module. 
There is no problem when i'm using `SqlCE`.

the error message is `ERROR: 42601: syntax error at or near "text"`

Thank you.

**Comment by bleroy** [comment]
Since the migration in this module isn't doing anything unconventional, I doubt this is a bug in the module. Having a full stack trace would help confirm or contradict that, but I'd bring the issue on the Orchard project itself. Thanks for reporting!

**Comment by LegendORC** [comment]
Thank you for helping, @bleroy.

I have looked at this.
Look like the `Orchard` has generated sql command like this :
`ALTER TABLE vandelay_industries_metarecord ALTER COLUMN description text`
This is work on `SqlCE` but not `PostgreSQL`.
for `PostgreSQL` should be like this :
`ALTER TABLE vandelay_industries_metarecord ALTER COLUMN description TYPE text`

**Comment by bleroy** [comment]
Yes, so that would definitely be on the Orchard side. I'm going to close this, then. Thanks again.
